### ISSUE TITLE
yolov7  모델 찾지 못하는 이슈

### ISSUE THREAD

**Issue by juwon8891** [somamvp/voyager-ml-server#5]
/run_fastapi.sh  스크립트로 실행하면 다음과 같이 모델을 찾지 못함.

지난번에도 해결했던거 같은데 방법 공유 차원에서 이슈 히스토리 남기는게 좋다고 생각.

> (base) soma3@soma3-Z490-UD:~/MVP/voyager-ml-server$ ./run_fastapi.sh 
process info:
/home/soma3/.zshrc:source:8: no such file or directory: /home/soma3/.zshrc
active environment : yolov7-env
현재 구동 중인 애플리케이션이 없으므로 종료하지 않습니다.
running script server_fast
INFO:     Will watch for changes in these directories: ['/home/soma3/MVP/voyager-ml-server']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [25476] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/soma3/anaconda3/envs/yolov7-env/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/soma3/anaconda3/envs/yolov7-env/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/soma3/anaconda3/envs/yolov7-env/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/soma3/anaconda3/envs/yolov7-env/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/soma3/anaconda3/envs/yolov7-env/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/soma3/anaconda3/envs/yolov7-env/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/soma3/anaconda3/envs/yolov7-env/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/soma3/anaconda3/envs/yolov7-env/lib/python3.10/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/soma3/anaconda3/envs/yolov7-env/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/soma3/anaconda3/envs/yolov7-env/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/soma3/anaconda3/envs/yolov7-env/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/soma3/MVP/voyager-ml-server/./server_fast.py", line 17, in <module>
    from yolov7.models.experimental import attempt_load
ModuleNotFoundError: No module named 'yolov7.models'
`

**Comment by juwon8891** [comment]
서브모듈 받으려고하면 yolov5는 받아와지는데, yolov7는 안됌.

Submodule path 'yolov5': checked out 'bc9fcb176734e63d02a1a677c9b2e66f08a2a040'
fatal: remote error: upload-pack: not our ref 99b0b3fca233395e8189f21f8ea054b080276191
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'yolov7', but it did not contain 99b0b3fca233395e8189f21f8ea054b080276191. Direct fetching of that commit failed.

**Comment by juwon8891** [comment]
git submodule update --force --recursive --init --remote 명령어로 위에는 해결
하지만 다음 오류

>  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/soma3/MVP/voyager-ml-server/./server_fast.py", line 18, in <module>
    from yolov7.utils.my_datasets import LoadStreams, LoadImages, LoadSingleImage
ModuleNotFoundError: No module named 'yolov7.utils.my_datasets'

**Comment by juwon8891** [comment]
![image](https://user-images.githubusercontent.com/74857614/191205294-73a182e8-c8b3-43eb-9e0e-d8bd2d62164e.png)

yolov7 remote main 브랜치랑 동기화는 잘됨.
yolov7 디렉토리내에서 무언가 수정한 것으로 보임
yolov7.utils.my_datasets을 yolov7 디렉토리가 아닌 루트 디렉토리에서 받아올 수 있게 해주세요.

**Comment by juwon8891** [comment]
이슈 해결
